### ISSUE TITLE
Titolo

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Search-Algorithms#38]
non sarebbe meglio un nome del tipo: AlgorithmAndDataStructure
o qualcosa del genere?

**Comment by DanerSound** [comment]
ci avevo pensato ma non è il punto principale della repo... se qualcuno cerca qualcosa cercherà sicuramente "sorting" o cose similli non credi ?... ma ora se vogliamo essere proprio formali possiamo scrivete come titolo : AlgorithmAndDataStructure-Sorting

**Comment by Wabri** [comment]
solitamente nelle ricerche non viene visualizzato il titolo come prima ricerca ma i tag associati alla repo, che puoi aggiungere in questa sezione: ![example](https://user-images.githubusercontent.com/12409541/37600924-0147f816-2b89-11e8-853a-4104c7a7f866.png)

**Comment by DanerSound** [comment]
allora facciamo cosi! cambiamo i nomi e mettiamo i tag giusto dato che fin ora non li abbiamo considerati

**Comment by Wabri** [comment]
cambia i nomi, la repository è la tua :smile:

**Comment by DanerSound** [comment]
pio
