### ISSUE TITLE
mathTools

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Search-Algorithms#40]
perchè non cambiare anche posizione al package [utility](https://github.com/DanerSound/Sort-Algorithms/tree/master/Search-algorithms/src/utility) facendolo diventare un nuovo project in cui vengono messi tutti i tool matematici necessari agli algoritmi e non solo? Magari potrebbero servire anche negli algoritmi di ricerca e quindi riutilizzarli anche in quel project non sarebbe male.

**Comment by DanerSound** [comment]
ho visto ora il messaggio : D

**Comment by DanerSound** [comment]
si! _mi piacie_!
